-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 18 Jun 2024 pada 11.13
-- Versi server: 10.4.32-MariaDB
-- Versi PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nama_hewan`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `hewan`
--

CREATE TABLE `hewan` (
  `id` int(11) NOT NULL,
  `nama_hewan` varchar(255) NOT NULL,
  `link_foto` varchar(255) NOT NULL,
  `link_foto2` varchar(255) NOT NULL,
  `penjelasan` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `hewan`
--

INSERT INTO `hewan` (`id`, `nama_hewan`, `link_foto`, `link_foto2`, `penjelasan`) VALUES
(1, 'antelope-antelope', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/antelope-antelope/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/antelope-antelope/2.jpg', 'Antelop adalah hewan yang bisa berlari sangat cepat di padang rumput. Mereka punya tanduk yang cantik dan sering hidup berkelompok. Antelop suka makan rumput dan daun-daunan. Ayo, bayangkan betapa cepatnya mereka berlari seperti kilat!'),
(2, 'badger-luak', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/badger-luak/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/badger-luak/2.jpg', 'Luak adalah hewan kecil yang suka menggali lubang di tanah. Mereka punya cakar kuat dan bulu tebal berwarna hitam dan putih. Luak sangat pandai mencari makanan di malam hari. Siap-siap bermain petak umpet dengan luak yang jago menggali!'),
(3, 'bat-kelelawar', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bat-kelelawar/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bat-kelelawar/2.jpg', 'Kelelawar adalah satu-satunya mamalia yang bisa terbang. Mereka aktif di malam hari dan suka makan buah atau serangga. Kelelawar juga membantu menyebarkan biji buah di hutan. Bayangkan mereka terbang sambil tertawa hehehe di malam hari!'),
(4, 'bear-beruang', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bear-beruang/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bear-beruang/2.jpg', 'Beruang adalah hewan besar dengan bulu lebat yang suka makan ikan dan madu. Mereka bisa berdiri di atas dua kaki dan suka tidur saat musim dingin. Beruang sangat kuat dan pandai memanjat pohon. Seru sekali melihat mereka mencari madu seperti Winnie the Pooh!'),
(5, 'bee-lebah', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bee-lebah/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bee-lebah/2.jpg', 'Lebah adalah serangga kecil yang suka terbang dari bunga ke bunga. Mereka membuat madu yang manis dan sangat berguna bagi tanaman. Lebah juga membantu penyerbukan tanaman agar bisa tumbuh. Bzzz... bayangkan lebah terbang sambil bernyanyi ceria!'),
(6, 'beetle-kumbang', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/beetle-kumbang/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/beetle-kumbang/2.jpg', 'Kumbang adalah serangga yang punya cangkang keras dan bisa berwarna-warni. Mereka bisa ditemukan di berbagai tempat seperti hutan dan taman. Kumbang suka makan daun, buah, atau serangga kecil lainnya. Kumbang bisa menjadi teman bermain yang lucu dan kuat!'),
(7, 'bison-bison', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bison-bison/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/bison-bison/2.jpg', 'Bison adalah hewan besar dengan tanduk kuat dan bulu tebal. Mereka suka hidup di padang rumput dan sangat kuat. Bison bisa berlari cepat meski tubuhnya besar. Bayangkan bison berlari sambil mengibaskan bulu tebalnya yang keren!'),
(8, 'boar-babihutan', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/boar-babihutan/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/boar-babihutan/2.jpg', 'Babi hutan adalah babi liar yang punya bulu kasar dan taring panjang. Mereka suka mencari makanan di hutan dan padang rumput. Babi hutan juga suka berkubang di lumpur untuk mendinginkan tubuh. Ayo bermain lumpur bersama babi hutan yang asyik ini!'),
(9, 'butterfly-kupukupu', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/butterfly-kupukupu/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/butterfly-kupukupu/2.jpg', 'Kupu-kupu adalah serangga cantik dengan sayap warna-warni. Mereka suka terbang di taman bunga dan berasal dari ulat. Kupu-kupu minum nektar dari bunga dengan belalai kecilnya. Lihatlah kupu-kupu menari-nari di udara dengan gembira!'),
(10, 'cat-kucing', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/cat-kucing/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/cat-kucing/2.jpg', 'Kucing adalah hewan peliharaan yang lucu dan suka bermain. Mereka punya cakar tajam dan sering mengeong untuk berkomunikasi. Kucing juga sangat pandai menangkap tikus. Mari bermain bola benang dengan kucing yang menggemaskan ini!'),
(11, 'caterpillar-ulat', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/caterpillar-ulat/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/caterpillar-ulat/2.jpg', 'Ulat adalah bayi kupu-kupu yang berbentuk seperti cacing dan suka makan daun. Mereka berubah menjadi kepompong sebelum menjadi kupu-kupu. Ulat sering ditemukan di tanaman kebun atau hutan. Ulat kecil yang lucu ini akan berubah menjadi kupu-kupu yang indah!'),
(12, 'chimpanzee-simpanse', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/chimpanzee-simpanse/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/chimpanzee-simpanse/2.jpg', 'Simpanse adalah hewan pintar yang mirip manusia. Mereka suka memanjat pohon dan menggunakan alat sederhana untuk mencari makanan. Simpanse hidup berkelompok dan saling membantu. Bayangkan simpanse bermain jungkat-jungkit di pohon tinggi!'),
(13, 'cockroach-kecoa', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/cockroach-kecoa/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/cockroach-kecoa/2.jpg', 'Kecoa adalah serangga yang bisa hidup hampir di mana saja. Mereka suka berlari cepat dan bisa hidup di tempat yang gelap dan lembap. Kecoa juga bisa bertahan hidup tanpa makan selama beberapa hari. Bayangkan kecoa berlari balapan dengan serangga lain, seru!'),
(14, 'cow-sapi', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/cow-sapi/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/cow-sapi/2.jpg', 'Sapi adalah hewan besar yang hidup di peternakan. Mereka suka makan rumput dan menghasilkan susu yang kita minum setiap hari. Sapi sering berbunyi \"moo\" dengan suara yang lucu.'),
(15, 'coyote-koyote', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/coyote-koyote/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/coyote-koyote/2.jpg', 'Koyote adalah hewan liar mirip dengan anjing. Mereka suka berkeliaran di padang rumput dan hutan mencari makanan. Koyote sering membuat suara seperti melolong di malam hari.'),
(16, 'crab-kepiting', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/crab-kepiting/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/crab-kepiting/2.jpg', 'Kepiting adalah hewan laut yang memiliki cangkang keras dan berjalan menyamping. Mereka suka tinggal di pantai dan kadang-kadang menggali pasir. Kepiting punya capit kuat yang terlihat unik.'),
(17, 'crow-gagak', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/crow-gagak/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/crow-gagak/2.jpg', 'Gagak adalah burung hitam yang pintar dan suka berkicau \"kra-kra\". Mereka sering terlihat di pohon atau terbang di langit. Gagak suka mencari makanan di mana saja.'),
(18, 'deer-rusa', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/deer-rusa/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/deer-rusa/2.jpg', 'Rusa adalah hewan yang anggun dengan tanduk yang indah. Mereka suka berlari di hutan dan padang rumput. Rusa biasanya sangat pemalu dan bergerak dengan cepat.'),
(19, 'dog-anjing', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/dog-anjing/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/dog-anjing/2.jpg', 'Anjing adalah teman setia manusia yang suka bermain. Mereka bisa menggonggong dan mengibas-ngibaskan ekor saat bahagia. Anjing suka sekali bermain dengan bola dan tulang.'),
(20, 'dolphin-lumbalumba', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/dolphin-lumbalumba/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/dolphin-lumbalumba/2.jpg', 'Lumba-lumba adalah hewan laut yang cerdas dan suka melompat-lompat di air. Mereka berkomunikasi dengan suara siulan yang khas. Lumba-lumba senang bermain dan sangat ramah.'),
(21, 'donkey-keledai', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/donkey-keledai/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/donkey-keledai/2.jpg', 'Keledai adalah hewan yang kuat dan bisa membawa beban berat. Mereka punya telinga panjang dan suara khas \"hee-haw\". Keledai sering membantu petani di ladang.'),
(22, 'dragonfly-capung', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/dragonfly-capung/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/dragonfly-capung/2.jpg', 'Capung adalah serangga dengan sayap indah yang terbang cepat di atas air. Mereka suka hinggap di daun dan bunga. Capung memiliki mata besar yang bisa melihat segala arah.'),
(23, 'duck-bebek', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/duck-bebek/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/duck-bebek/2.jpg', 'Bebek adalah burung yang suka berenang di kolam dan sungai. Mereka berbunyi \"kwek-kwek\" dan punya kaki berselaput untuk berenang. Bebek suka makan biji-bijian dan serangga kecil.'),
(24, 'eagle-elang', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/eagle-elang/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/eagle-elang/2.jpg', 'Elang adalah burung besar dengan penglihatan tajam. Mereka terbang tinggi di langit dan suka berburu dari ketinggian. Elang memiliki cakar yang kuat dan paruh tajam.'),
(25, 'elephant-gajah', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/elephant-gajah/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/elephant-gajah/2.jpg', 'Gajah adalah hewan darat terbesar dengan telinga besar dan belalai panjang. Mereka suka makan daun dan buah-buahan. Gajah sangat kuat dan bisa mengangkat beban berat dengan belalainya.'),
(26, 'flamingo-flamingo', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/flamingo-flamingo/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/flamingo-flamingo/2.jpg', 'Flamingo adalah burung yang cantik dengan bulu berwarna merah muda. Mereka suka berdiri di satu kaki dan mencari makan di air dangkal. Flamingo sering terlihat dalam kelompok besar.'),
(27, 'fly-lalat', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/fly-lalat/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/fly-lalat/2.jpg', 'Lalat adalah serangga kecil yang suka terbang cepat di sekitar kita. Mereka memiliki mata besar yang bisa melihat segala arah. Lalat sering mencari makanan di tempat yang manis dan berbau. Mari terbang bersama lalat yang lincah dan penuh petualangan!'),
(28, 'fox-rubah', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/fox-rubah/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/fox-rubah/2.jpg', 'Rubah adalah hewan yang cerdas dengan bulu berwarna merah cerah. Mereka suka berburu di malam hari dan tinggal di lubang yang mereka gali sendiri. Rubah punya ekor panjang yang cantik dan berbulu lebat. Bayangkan rubah bermain petak umpet di hutan yang seru!'),
(29, 'goat-kambing', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/goat-kambing/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/goat-kambing/2.jpg', 'Kambing adalah hewan yang suka memanjat dan makan rumput hijau. Mereka memiliki tanduk kecil dan suka membuat suara \"mbee\" yang lucu. Kambing sering melompat-lompat dengan riang di padang rumput. Ayo melompat-lompat bersama kambing yang ceria ini!'),
(30, 'goldfish-ikanmas', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/goldfish-ikanmas/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/goldfish-ikanmas/2.jpg', 'Ikan mas adalah ikan kecil yang berwarna emas cerah dan cantik. Mereka suka berenang di akuarium dan bergerak dengan anggun. Ikan mas sangat suka makan pelet kecil dan berenang bersama teman-temannya. Mari berenang bersama ikan mas yang cantik dan berkilau!'),
(31, 'goose-angsa', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/goose-angsa/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/goose-angsa/2.jpg', 'Angsa adalah burung besar dengan leher panjang dan anggun. Mereka suka berenang di danau dan membuat suara \"honk\" yang khas. Angsa sering terlihat berenang bersama keluarganya dengan rapi. Bayangkan angsa berenang seperti kapal layar di atas danau!'),
(32, 'gorilla-gorila', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/gorilla-gorila/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/gorilla-gorila/2.jpg', 'Gorila adalah hewan besar yang kuat dengan bulu hitam tebal. Mereka suka makan buah-buahan dan duduk bersama keluarga mereka. Gorila sangat pintar dan bisa menggunakan alat sederhana untuk mencari makanan. Ayo bermain dan belajar bersama gorila yang bijak dan kuat!'),
(33, 'grasshopper-belalang', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/grasshopper-belalang/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/grasshopper-belalang/2.jpg', 'Belalang adalah serangga kecil yang bisa melompat jauh dengan kakinya yang kuat. Mereka suka makan daun-daunan dan sering mengeluarkan suara khas di malam hari. Belalang bisa terbang dengan sayap tipisnya yang indah. Mari melompat tinggi dan terbang bersama belalang yang ceria!'),
(34, 'hamster-hamster', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hamster-hamster/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hamster-hamster/2.jpg', 'Hamster adalah hewan kecil yang lucu dengan pipi yang bisa menyimpan makanan. Mereka suka bermain roda dan menggali terowongan kecil. Hamster sangat suka makan biji-bijian dan sayuran segar. Bayangkan hamster berputar-putar di roda sambil tersenyum lucu!'),
(35, 'hare-kelinciliar', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hare-kelinciliar/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hare-kelinciliar/2.jpg', 'Kelinci liar adalah hewan yang bisa berlari sangat cepat dan melompat tinggi. Mereka punya telinga panjang dan suka makan rumput dan sayuran. Kelinci liar hidup di padang rumput dan hutan. Ayo berlari kencang bersama kelinci liar yang gesit dan lincah!'),
(36, 'hedgehog-landak', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hedgehog-landak/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hedgehog-landak/2.jpg', 'Landak adalah hewan kecil dengan duri-duri tajam di punggungnya. Mereka suka makan serangga dan buah-buahan. Landak bisa menggulung tubuhnya menjadi bola ketika merasa terancam. Mari bermain gulung-gulung bersama landak yang unik dan lucu!'),
(37, 'hippopotamus-kudanil', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hippopotamus-kudanil/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hippopotamus-kudanil/2.jpg', 'Kuda nil adalah hewan besar yang suka menghabiskan waktu di air. Mereka punya mulut lebar dan gigi besar yang kuat. Kuda nil bisa berlari cepat meski tubuhnya besar. Bayangkan kuda nil bermain air dan menyemprotkan air seperti pancuran yang lucu!'),
(38, 'hornbill-rangkong', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hornbill-rangkong/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hornbill-rangkong/2.jpg', 'Rangkong adalah burung dengan paruh besar yang unik dan berwarna-warni. Mereka suka tinggal di hutan dan makan buah-buahan. Rangkong punya suara khas yang bisa terdengar dari jauh. Mari bayangkan rangkong terbang di hutan sambil bernyanyi riang!'),
(39, 'horse-kuda', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/horse-kuda/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/horse-kuda/2.jpg', 'Kuda adalah hewan yang kuat dan cepat dengan bulu yang halus. Mereka suka berlari di padang rumput dan bisa membawa orang atau barang di punggungnya. Kuda sering terlihat berlari dengan anggun dan bebas. Ayo berkuda bersama kuda yang gagah dan cepat seperti angin!'),
(40, 'hummingbird-burungkolibri', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hummingbird-burungkolibri/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hummingbird-burungkolibri/2.jpg', 'Burung kolibri adalah burung kecil yang sangat istimewa karena bisa terbang mundur! Mereka suka minum nektar dari bunga dan memiliki jantung yang berdebar sangat cepat, seperti saat kita berlari kencang.'),
(41, 'hyena-hyena', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hyena-hyena/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/hyena-hyena/2.jpg', 'Hyena adalah hewan yang pintar dan hidup berkelompok. Mereka suka tertawa dengan suara khas yang terdengar seperti tawa manusia! Hyena juga sangat kuat dan bisa makan hampir semua bagian hewan, termasuk tulangnya.'),
(42, 'jellyfish-uburubur', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/jellyfish-uburubur/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/jellyfish-uburubur/2.jpg', 'Ubur-ubur adalah hewan laut yang terlihat seperti payung transparan yang berenang di air. Mereka tidak memiliki otak atau jantung, tetapi bisa bergerak dan menangkap makanan menggunakan tentakel mereka. Beberapa jenis ubur-ubur bahkan bisa bersinar di dalam gelap!'),
(43, 'kangaroo-kanguru', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/kangaroo-kanguru/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/kangaroo-kanguru/2.jpg', 'Kanguru adalah hewan berkantong dari Australia yang suka melompat dengan kaki kuatnya. Bayi kanguru, yang disebut joey, hidup di dalam kantong ibunya sampai cukup besar untuk keluar. Kanguru juga bisa menggunakan ekornya yang kuat untuk menjaga keseimbangan saat melompat jauh!'),
(44, 'koala-koala', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/koala-koala/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/koala-koala/2.jpg', 'Koala adalah hewan lucu dari Australia yang suka memanjat pohon dan tidur sepanjang hari. Mereka makan daun eukaliptus yang memberikan mereka semua nutrisi yang dibutuhkan. Koala juga memiliki kantong di perutnya untuk membawa bayi mereka yang disebut joey.'),
(45, 'ladybugs-kumbangkoksi', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/ladybugs-kumbangkoksi/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/ladybugs-kumbangkoksi/2.jpg', 'Kumbang koksi adalah serangga kecil dengan warna cerah dan bintik hitam yang cantik. Mereka suka memakan serangga kecil seperti kutu daun yang merusak tanaman, sehingga dianggap sebagai sahabat petani. Ketika merasa terancam, kumbang koksi bisa mengeluarkan cairan berbau dari kakinya untuk melindungi diri.'),
(46, 'leopard-macantutul', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/leopard-macantutul/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/leopard-macantutul/2.jpg', 'Macan tutul adalah kucing besar yang pandai memanjat pohon dan suka bersembunyi di antara dedaunan. Bulu mereka memiliki pola bintik-bintik unik yang membantu mereka menyamar di alam liar. Macan tutul adalah pemburu yang gesit dan bisa berlari dengan sangat cepat untuk menangkap mangsanya.'),
(47, 'lion-singa', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/lion-singa/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/lion-singa/2.jpg', 'Singa adalah kucing besar yang dikenal sebagai \"raja hutan\" dengan surai tebal pada jantan yang membuatnya terlihat gagah. Mereka hidup berkelompok yang disebut kebanggaan, di mana betina bekerja sama untuk berburu makanan. Suara auman singa bisa terdengar hingga lima mil jauhnya, menunjukkan kekuatan dan keberadaannya.'),
(48, 'lizard-kadal', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/lizard-kadal/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/lizard-kadal/2.jpg', 'Kadal adalah hewan kecil dengan kulit bersisik dan bisa merayap di dinding atau pepohonan. Mereka suka berjemur di bawah sinar matahari untuk menghangatkan tubuhnya. Beberapa kadal bahkan bisa memutuskan ekornya untuk melarikan diri dari predator dan kemudian menumbuhkannya kembali!'),
(49, 'lobster-lobster', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/lobster-lobster/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/lobster-lobster/2.jpg', 'Lobster adalah hewan laut dengan cangkang keras dan cakar tajam. Mereka hidup di dasar laut dan dapat berubah warna dari biru kehijauan hingga merah cerah setelah dimasak. Lobster memiliki antena panjang untuk merasakan makanan dan lingkungan sekitarnya, serta cakar kuat yang digunakan untuk memecahkan makanan dan membela diri.'),
(50, 'mosquito-nyamuk', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/mosquito-nyamuk/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/mosquito-nyamuk/2.jpg', 'Nyamuk adalah serangga kecil dengan sayap yang bisa terbang. Mereka suka menghisap darah untuk hidup dan bisa membuat gatal jika mereka menggigit. Penting untuk memakai lotion anti-nyamuk agar terhindar dari gigitan mereka!'),
(51, 'moth-ngengat', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/moth-ngengat/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/moth-ngengat/2.jpg', 'Ngengat adalah serangga kecil yang sering kali berwarna-warni dan memiliki sayap yang lebar. Mereka suka terbang di malam hari dan mengejar cahaya. Ngengat juga bisa sangat berbeda bentuk dan warnanya, membuat mereka seru untuk diamati!'),
(52, 'mouse-tikus', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/mouse-tikus/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/mouse-tikus/2.jpg', 'Tikus adalah hewan kecil dengan telinga besar dan ekor panjang. Mereka pintar dan suka menjelajah di sekitar rumah mencari makanan seperti biji-bijian dan keju. Meskipun sering kali dianggap mengganggu, tikus dapat menjadi teman yang cerdas untuk dipelihara dalam kandang!'),
(53, 'octopus-gurita', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/octopus-gurita/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/octopus-gurita/2.jpg', 'Gurita adalah hewan laut yang pintar dengan delapan lengan panjang. Mereka bisa berubah warna untuk bersembunyi dari musuh dan bisa menyemprotkan tinta hitam untuk melarikan diri. Gurita suka tinggal di dasar laut dan makan kepiting serta ikan kecil.'),
(54, 'okapi-okapi', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/okapi-okapi/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/okapi-okapi/2.jpg', 'Okapi adalah hewan unik yang mirip dengan jerapah tetapi lebih pendek dan memiliki garis-garis seperti zebra di kakinya. Mereka hidup di hutan hujan di Afrika dan makan daun serta buah-buahan.'),
(55, 'orangutan-orangutan', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/orangutan-orangutan/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/orangutan-orangutan/2.jpg', 'Orangutan adalah kera besar dengan lengan yang sangat panjang. Mereka hidup di hutan hujan dan menghabiskan banyak waktu di pohon-pohon. Orangutan suka makan buah-buahan, daun, dan serangga.'),
(56, 'otter-berangberang', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/otter-berangberang/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/otter-berangberang/2.jpg', 'Berang-berang adalah hewan yang suka berenang dan bermain di air. Mereka memiliki bulu yang tebal untuk menjaga tubuh tetap hangat. Berang-berang suka makan ikan dan kerang-kerangan.'),
(57, 'owl-burunghantu', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/owl-burunghantu/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/owl-burunghantu/2.jpg', 'Burung hantu adalah burung yang aktif di malam hari. Mereka memiliki mata besar yang bisa melihat dalam gelap dan telinga yang tajam untuk mendengar mangsa. Burung hantu makan tikus, serangga, dan binatang kecil lainnya.'),
(58, 'ox-lembu', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/ox-lembu/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/ox-lembu/2.jpg', 'Lembu adalah hewan besar yang kuat. Mereka digunakan untuk membantu petani menggarap sawah dan mengangkut barang. Lembu makan rumput dan tanaman.'),
(59, 'oyster-tiram', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/oyster-tiram/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/oyster-tiram/2.jpg', 'Tiram adalah hewan laut yang hidup di dalam cangkang keras. Mereka bisa menghasilkan mutiara yang indah di dalam cangkangnya. Tiram makan plankton dengan menyaring air laut.'),
(60, 'panda-panda', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/panda-panda/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/panda-panda/2.jpg', 'Panda adalah beruang lucu dengan bulu hitam dan putih. Mereka hidup di hutan bambu di Tiongkok dan suka makan bambu. Panda adalah hewan yang pemalu dan suka tidur.'),
(61, 'parrot-burungbeo', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/parrot-burungbeo/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/parrot-burungbeo/2.jpg', 'Burung beo adalah burung berwarna-warni yang pandai meniru suara. Mereka suka tinggal di hutan tropis dan makan buah-buahan, kacang-kacangan, serta biji-bijian.'),
(62, 'pelecaniformes-burungpelikan', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/pelecaniformes-burungpelikan/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/pelecaniformes-burungpelikan/2.jpg', 'Burung pelikan adalah burung besar dengan paruh panjang yang memiliki kantong besar. Mereka menggunakan kantong ini untuk menangkap ikan di air. Burung pelikan hidup di dekat air seperti danau dan laut.'),
(63, 'penguin-pinguin', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/penguin-pinguin/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/penguin-pinguin/2.jpg', 'Pinguin adalah burung yang tidak bisa terbang tetapi sangat pandai berenang. Mereka hidup di daerah dingin seperti Antartika. Pinguin suka makan ikan dan cumi-cumi.'),
(64, 'pig-babi', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/pig-babi/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/pig-babi/2.jpg', 'Babi adalah hewan yang cerdas dan suka bermain. Mereka suka menggali tanah dengan hidungnya untuk mencari makanan. Babi makan berbagai jenis makanan termasuk buah-buahan, sayuran, dan sisa makanan.'),
(65, 'pigeon-merpati', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/pigeon-merpati/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/pigeon-merpati/2.jpg', 'Merpati adalah burung yang sering kita lihat di kota-kota. Mereka pandai menemukan jalan pulang meski sudah pergi jauh. Merpati makan biji-bijian, kacang-kacangan, dan remah-remah makanan.'),
(66, 'porcupine-landak', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/porcupine-landak/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/porcupine-landak/2.jpg', 'Landak adalah hewan mamalia yang termasuk dalam ordo Rodentia, yang terkenal dengan ciri khas duri-duri tajam yang menutupi tubuhnya. Duri-duri ini sebenarnya adalah rambut yang termodifikasi dan berfungsi sebagai mekanisme pertahanan terhadap predator. Landak termasuk hewan yang unik dengan mekanisme pertahanan yang luar biasa dan kemampuan adaptasi yang tinggi, menjadikannya subjek yang menarik bagi banyak penggemar alam dan ilmuwan.'),
(67, 'possum-posum', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/possum-posum/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/possum-posum/2.jpg', 'Posum adalah sekelompok mamalia marsupial yang termasuk dalam ordo Diprotodontia, subordo Phalangeriformes. Mereka berasal dari Australia, Papua Nugini, dan wilayah sekitarnya, serta telah diperkenalkan ke Selandia Baru. Posum memiliki tubuh yang kecil hingga sedang, dengan panjang antara 20 hingga 55 cm, tergantung pada spesiesnya. Posum memiliki perilaku nokturnal, yang berarti mereka aktif pada malam hari dan tidur pada siang hari.'),
(68, 'raccoon-rakun', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/raccoon-rakun/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/raccoon-rakun/2.jpg', 'Rakun adalah mamalia kecil yang termasuk dalam famili Procyonidae dan dikenal dengan nama ilmiah Procyon lotor. Hewan ini berasal dari Amerika Utara, namun telah menyebar ke berbagai bagian dunia, termasuk Eropa dan Jepang. Rakun merupakan hewan yang memiliki kemampuan adaptasi yang luar biasa, kecerdasan tinggi, dan perilaku unik yang membuat mereka menjadi subjek yang menarik untuk dipelajari dan diamati dalam ekosistem alami maupun perkotaan.'),
(69, 'rat-tikus', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/rat-tikus/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/rat-tikus/2.jpg', 'Tikus merupakan hewan pengerat (Rodentia) yang tergolong dalam famili Muridae. Hewan ini terkenal sebagai hama yang sering mengganggu manusia. Ukuran tubuh tikus bervariasi, tergantung spesiesnya. Tikus rumah (Rattus rattus) yang biasa ditemukan di rumah memiliki panjang tubuh sekitar 15-20 cm, sedangkan tikus got (Rattus norvegicus) yang lebih besar bisa mencapai panjang 20-25 cm. Tikus adalah hewan pemakan segala (omnivora), yang berarti mereka memakan berbagai macam makanan, termasuk biji-bijian, buah-buahan, serangga, dan daging.'),
(70, 'reindeer-rusakutub', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/reindeer-rusakutub/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/reindeer-rusakutub/2.jpg', 'Rusa kutub, yang juga dikenal sebagai karibu di Amerika Utara, adalah spesies rusa yang tersebar di sekitar wilayah kutub bumi, seperti Arktik, subarktik, tundra, daerah boreal, dan pegunungan utara Eropa, Siberia, dan Amerika Utara. Rusa kutub adalah perenang yang handal dan dapat berenang sejauh beberapa kilometer untuk mencari makanan atau melarikan diri dari predator.'),
(71, 'rhinoceros-badak', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/rhinoceros-badak/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/rhinoceros-badak/2.jpg', 'Badak adalah mamalia herbivora besar yang berasal dari Afrika dan Asia. Mereka terkenal dengan culanya yang besar dan kuat, yang terbuat dari keratin. Kulit badak tebal dan berwarna abu-abu, coklat, atau hitam. Kulit ini terbagi menjadi beberapa lempengan yang menyerupai baju zirah, memberikan perlindungan dari predator.'),
(72, 'sandpiper-trinil', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/sandpiper-trinil/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/sandpiper-trinil/2.jpg', 'Trinil adalah jenis burung yang terdiri dari dua jenis yaitu Trinil Bedaran dan Trinil Green-Laged Tringa. Trinil Bedaran memiliki bulu berwarna abu-abu di bagian atas dan putih di bagian bawah, dengan mahkota hitam dan garis putih di atas mata. Sementara Trinil Green-Laged Tringa memiliki bulu berwarna abu-abu di bagian atas dan putih di bagian bawah, dengan dada bergaris dan garis putih di atas mata.'),
(73, 'seahorse-kudalaut', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/seahorse-kudalaut/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/seahorse-kudalaut/2.jpg', 'Kuda laut adalah hewan unik ini terkenal dengan bentuk kepalanya yang menyerupai kuda dan kemampuannya untuk berenang tegak lurus di air. Hewan memiliki bentuk kepala yang khas, menyerupai kuda, dengan moncong kecil dan mata yang dapat bergerak secara independen. Mereka memiliki penglihatan yang tajam dan dapat melihat mangsanya dari jarak jauh.'),
(74, 'seal-anjinglaut', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/seal-anjinglaut/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/seal-anjinglaut/2.jpg', 'Anjing laut adalah mamalia laut semi-akuatik yang tergolong dalam ordo Carnivora. Mereka terkenal dengan tubuhnya yang gemuk dan berbulu, sirip kaki mereka yang kuat, dan kemampuannya untuk berenang dengan anggun di air dan berjalan dengan canggung di darat. Anjing laut memiliki kumis yang sensitif yang membantu mereka mendeteksi mangsa dan menavigasi di air yang keruh.'),
(75, 'shark-hiu', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/shark-hiu/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/shark-hiu/2.jpg', 'Hiu terkenal dengan bentuk tubuhnya yang ramping dan torpedo, siripnya yang kuat, dan giginya yang tajam. Hiu memiliki penglihatan yang tajam dan dapat mendeteksi mangsa dari jarak jauh. Hiu memiliki indra penciuman yang sangat kuat, yang membantu mereka menemukan mangsa dan menavigasi di bawah air. Hiu sering digambarkan sebagai predator berbahaya dalam film dan media, dan ini telah menyebabkan ketakutan dan kebencian yang tidak rasional terhadap hiu pada banyak orang.'),
(76, 'sheep-domba', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/sheep-domba/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/sheep-domba/2.jpg', 'Domba adalah hewan ini terkenal dengan bulunya yang tebal dan keriting, yang disebut wol, dan tanduknya yang bercabang. Domba adalah hewan herbivora dan memakan berbagai macam tanaman, seperti rumput, daun, dan buah-buahan. Susu domba digunakan untuk membuat keju, yogurt, dan mentega. Kulit domba digunakan untuk membuat sepatu, tas, dan jaket.'),
(77, 'snake-ular', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/snake-ular/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/snake-ular/2.jpg', 'Ular adalah hewan reptil bertubuh panjang tanpa kaki yang tergolong dalam subordo Serpentes. Hewan melata ini terkenal dengan bentuk tubuhnya yang ramping dan memanjang, sisiknya yang halus, dan lidahnya yang bercabang. Serangan ular terhadap manusia jarang terjadi, dan sebagian besar serangan tidak berakibat fatal. Racun ular digunakan dalam penelitian medis untuk mengembangkan obat-obatan baru.'),
(78, 'sparrow-burunggereja', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/sparrow-burunggereja/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/sparrow-burunggereja/2.jpg', 'Burung gereja adalah keluarga burung pipit kecil yang dikenal dengan ukurannya yang kecil, bulunya yang berwarna coklat-abu-abu, dan suaranya yang ceria. Burung gereja adalah omnivora dan memakan berbagai macam makanan, termasuk biji-bijian, serangga, buah-buahan, dan sisa makanan manusia.'),
(79, 'squid-cumicumi', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/squid-cumicumi/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/squid-cumicumi/2.jpg', 'Cumi-cumi adalah hewan laut dengan tubuh panjang dan tentakel yang banyak. Mereka bisa menyemprotkan tinta untuk melindungi diri dari musuh. Cumi-cumi bisa berenang cepat dengan cara menggerakkan tubuh mereka.'),
(80, 'squirrel-tupai', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/squirrel-tupai/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/squirrel-tupai/2.jpg', 'Tupai adalah hewan kecil yang suka memanjat pohon. Mereka punya ekor lebat dan sering terlihat mengumpulkan kacang. Tupai bisa melompat dari cabang ke cabang dengan sangat cepat.'),
(81, 'starfish-bintanglaut', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/starfish-bintanglaut/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/starfish-bintanglaut/2.jpg', 'Bintang laut adalah hewan laut yang berbentuk seperti bintang. Mereka punya lima lengan dan bisa merayap di dasar laut. Bintang laut suka makan kerang kecil dan tumbuhan laut.'),
(82, 'swan-angsa', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/swan-angsa/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/swan-angsa/2.jpg', 'Angsa adalah burung besar dengan leher panjang dan bulu putih yang anggun. Mereka suka berenang di danau dan sungai. Angsa terkenal dengan suaranya yang merdu dan tarian airnya.'),
(83, 'tiger-harimau', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/tiger-harimau/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/tiger-harimau/2.jpg', 'Harimau adalah kucing besar dengan garis-garis hitam di tubuhnya. Mereka suka berkeliaran di hutan dan berburu mangsa. Harimau sangat kuat dan bisa berlari dengan cepat.'),
(84, 'turkey-kalkun', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/turkey-kalkun/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/turkey-kalkun/2.jpg', 'Kalkun adalah burung besar yang sering berbunyi \"gobble-gobble\". Mereka punya bulu berwarna-warni dan ekor yang lebar. Kalkun suka berjalan-jalan di hutan dan padang rumput.'),
(85, 'turtle-kurakura', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/turtle-kurakura/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/turtle-kurakura/2.jpg', 'Kura-kura adalah hewan dengan cangkang keras di punggungnya. Mereka bergerak lambat dan suka tinggal di air maupun darat. Kura-kura bisa hidup sangat lama.'),
(86, 'whale-paus', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/whale-paus/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/whale-paus/2.jpg', 'Paus adalah hewan laut terbesar dengan tubuh yang sangat besar. Mereka bisa bernyanyi di bawah air dengan suara yang merdu. Paus suka berenang jauh di lautan luas.'),
(87, 'wolf-serigala', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/wolf-serigala/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/wolf-serigala/2.jpg', 'Serigala adalah hewan liar yang mirip dengan anjing. Mereka hidup dalam kelompok yang disebut kawanan. Serigala suka berburu bersama-sama dan bisa melolong dengan keras.'),
(88, 'wombat-wombat', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/wombat-wombat/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/wombat-wombat/2.jpg', 'Wombat adalah hewan berbulu tebal yang hidup di Australia. Mereka suka menggali liang di tanah dan makan tumbuhan. Wombat punya kaki pendek dan cakar kuat.'),
(89, 'woodpecker-pelatuk', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/woodpecker-pelatuk/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/woodpecker-pelatuk/2.jpg', 'Pelatuk adalah burung yang suka mematuk batang pohon untuk mencari serangga. Mereka punya paruh kuat dan kepala yang bisa bergerak cepat. Pelatuk sering terdengar \"tok-tok-tok\" di hutan.'),
(90, 'zebra-zebra', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/zebra-zebra/1.jpg', 'https://storage.cloud.google.com/dataset-teamgrowup/animals2/new/zebra-zebra/2.jpg', 'Zebra adalah hewan dengan tubuh bergaris-garis hitam dan putih. Mereka suka hidup berkelompok di padang rumput. Zebra bisa berlari cepat untuk menghindari bahaya.');
(91, 'human', '', '', ''),
(92, 'none', '', '', '')
--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `hewan`
--
ALTER TABLE `hewan`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `hewan`
--
ALTER TABLE `hewan`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=91;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
